version: '3'
services:
  frontend:
    # ./nuxt/Dockerfileをもとにnuxtコンテナを作成する
    build:
      context: ./.docker/frontend
    # 特権モードを有効にしておく(いらないかも)
    privileged: true
    # コンテナ外部からport3000でアクセスできるようにする
    volumes:
      - ./app:/app:cached
    environment:
        - HOST=${DOCKER_PUBLIC_IP-0.0.0.0}
    ports:
      - '3033:3000'
    # コンテナ起動時のコマンド
    command: ['yarn', 'run', 'dev']

